import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { SiteFooter, SiteHeader } from '@/components/site-chrome';

export const metadata: Metadata = { title: 'Projects — nicobecodin', description: 'Selected work in market infrastructure, decentralized exchanges, Solana privacy, C++ and multicore systems.', alternates: { canonical: `${process.env.NEXT_PUBLIC_SITE_URL || 'https://nicobecodin.github.io'}/projects/` } };

const projects = [
  {id:'light-dex', number:'01', type:'RUST / DISTRIBUTED SYSTEMS', name:'Light DEX', status:'CURRENTLY BUILDING', text:'A learning project that starts with process-based nodes and PBFT-style consensus, then moves into deterministic exchange state, transfers and an order book. I use the build log to examine the implementation decisions and failure cases.', link:'/writing/building-a-dex-part-1', label:'Read the build log', sourceLink:'https://github.com/NicoBeCodin/light_dex', detail:'Rust · TCP · PBFT · exchange state'},
  {id:'market-making', number:'02', type:'RUST / TRADING INFRASTRUCTURE', name:'Multi-venue market making', status:'PRIVATE RESEARCH PROJECT', text:'A VPS-based research and execution system across crypto venues. My work includes a shared market-data hub, venue adapters, order lifecycle and inventory reconciliation, and shadow-versus-live fill analysis. Research estimates and realised trading results are kept separate.', link:null, label:null, detail:'Rust · market data · OMS · research'},
  {id:'solana-arbitrage', number:'03', type:'RUST / SOLANA / EXECUTION', name:'Solana arbitrage bot', status:'PROTOTYPE', text:'A prototype exploring two-hop and triangular routes on Solana, with pool discovery and Jupiter routing. The work examines quote discovery, route construction and the execution constraints behind an apparent spread.', link:null, label:null, detail:'Rust · Solana · routing'},
  {id:'leafpay', number:'04', type:'SOLANA / ZERO KNOWLEDGE', name:'LeafPay', status:'HACKATHON FINALIST', text:'A Solana privacy-pool prototype using a Merkle Mountain Range, memo-based leaf discovery and client-side proof generation. It reached the final round of a Colosseum hackathon. The prototype is not presented as audited production software.', link:'https://github.com/NicoBeCodin/solana_mixer', label:'View source', detail:'Rust · Solana · zero knowledge'},
  {id:'multicore', number:'05', type:'C / C++ / SYSTEMS', name:'Multicore primitives', status:'EXPERIMENTS', text:'Exercises with locks, lock-free algorithms, ring buffers and transactional memory. These are deliberately small experiments in synchronization and memory behavior.', link:'https://github.com/NicoBeCodin/multicore_architecture', label:'View source', detail:'C · C++ · concurrency'},
  {id:'trees', number:'06', type:'C++ / MACHINE LEARNING', name:'Tree ensembles', status:'RESEARCH PROJECT', text:'From-scratch regression trees, bagging and boosting with parallel experiments and benchmark tooling. The work explores algorithm design and performance rather than treating a library call as the result.', link:'https://github.com/NicoBeCodin/decision_tree_ensemble_model', label:'View source', detail:'C++ · OpenMP · MPI · benchmarking'},
];

export default function ProjectsPage() { return <main><div className="page-shell"><SiteHeader/><section className="interior-hero projects-intro"><h1 className="sr-only">Projects</h1><p>Some are ongoing, some were experiments, and all of them taught me something worth keeping.</p></section><section className="project-grid" aria-label="Projects">{projects.map(project => <article className="project-card" id={project.id} key={project.id}><div className="project-card-top"><span>{project.number} / {project.type}</span><span className="project-status">{project.status}</span></div><h2>{project.name}</h2><p>{project.text}</p><div className="project-card-bottom"><span>{project.detail}</span><div className="project-card-links">{project.link && (project.link.startsWith('http') ? <a href={project.link} target="_blank" rel="noreferrer">{project.label} <ArrowUpRight size={16}/></a> : <Link href={project.link}>{project.label} <ArrowUpRight size={16}/></Link>)}{'sourceLink' in project && project.sourceLink && <a href={project.sourceLink} target="_blank" rel="noreferrer">View source <ArrowUpRight size={16}/></a>}</div></div></article>)}</section><SiteFooter/></div></main>; }
